// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  /// API keys here are for project identification, not authorization.
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCt6H4kd7CEcbE5ikJuZzW27p6nhd7hLX8',
    appId: '1:246277448750:web:cfe7966b21abffeed3abbf',
    messagingSenderId: '246277448750',
    projectId: 'eargpt-b0987',
    authDomain: 'eargpt-b0987.firebaseapp.com',
    storageBucket: 'eargpt-b0987.firebasestorage.app',
    measurementId: 'G-79YYRVJELN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA9Mbmo9YxVDINxmzkiTAaeUzCkMHSdrGc',
    appId: '1:246277448750:android:ac136273d6b26660d3abbf',
    messagingSenderId: '246277448750',
    projectId: 'eargpt-b0987',
    storageBucket: 'eargpt-b0987.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC0ceBylHqaCICBS4l1jK8BLrgy3GUgVmg',
    appId: '1:246277448750:ios:acabe9972b07dd34d3abbf',
    messagingSenderId: '246277448750',
    projectId: 'eargpt-b0987',
    storageBucket: 'eargpt-b0987.firebasestorage.app',
    iosBundleId: 'edu.kit.teco.openWearable',
  );
}