// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyABlFDGt2_8ObSQlrPBcQ83NHt21RcUpq8',
    appId: '1:347898558963:web:751019c2434ff9b3427a86',
    messagingSenderId: '347898558963',
    projectId: 'eargpt-1cef3',
    authDomain: 'eargpt-1cef3.firebaseapp.com',
    storageBucket: 'eargpt-1cef3.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBhOM8Bw8Ig0X7TWHzReWLGlgUpo5bBCKI',
    appId: '1:347898558963:android:229f6b9ee692ac96427a86',
    messagingSenderId: '347898558963',
    projectId: 'eargpt-1cef3',
    storageBucket: 'eargpt-1cef3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCRe1UkLugtjMs4O5N4UAekx_QZiBBSHjQ',
    appId: '1:347898558963:ios:155c5dccb5c1f9aa427a86',
    messagingSenderId: '347898558963',
    projectId: 'eargpt-1cef3',
    storageBucket: 'eargpt-1cef3.firebasestorage.app',
    iosBundleId: 'edu.kit.teco.openWearable',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCRe1UkLugtjMs4O5N4UAekx_QZiBBSHjQ',
    appId: '1:347898558963:ios:155c5dccb5c1f9aa427a86',
    messagingSenderId: '347898558963',
    projectId: 'eargpt-1cef3',
    storageBucket: 'eargpt-1cef3.firebasestorage.app',
    iosBundleId: 'edu.kit.teco.openWearable',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyABlFDGt2_8ObSQlrPBcQ83NHt21RcUpq8',
    appId: '1:347898558963:web:08c5c568b83fa5fd427a86',
    messagingSenderId: '347898558963',
    projectId: 'eargpt-1cef3',
    authDomain: 'eargpt-1cef3.firebaseapp.com',
    storageBucket: 'eargpt-1cef3.firebasestorage.app',
  );
}
